add query handling to /api/articles endpoint
robert-matthew-brooks/be-nc-news pull request #13
Opened 2023-06-29 14:35 UTC by robert-matthew-brooks

2023-06-29 15:20 UTC, NRMSMITH requested changes
SQL injection needs sorting!

2023-06-29 15:20 UTC, NRMSMITH commented on __tests__/app.test.js
> +    test('200: should have an empty array when filtered by topic "not_a_topic"', () => {
I think an invalid topic should really give a 404, otherwise we could risk SQL injection

2023-06-29 15:20 UTC, NRMSMITH commented on models/articles.models.js
> +        WHERE lower(articles.topic) LIKE $1
articles.topic is sql injection. Someone could write drop db and you'd lose your entire database

2023-06-30 08:21 UTC, Slyose reviewed
One tweak i'd like to see to make your sort by checks more dynamic and less repetitive. But feel free to merge independently afterwards!

2023-06-30 08:21 UTC, Slyose commented on models/util.js
> +        sort_by: ['author', 'title', 'article_id', 'topic', 'created_at', 'votes', 'article_img_url', 'comment_count'],
Id say that some of these aren't needed, for example article_img_url, why would the user want to sort by the url that links to the article image? ArticleID also has very little relevance to a user (it's more for your api to keep track of which is which). Other sort_by's look good!

2023-06-30 08:21 UTC, Slyose commented on models/util.js
> +}
This part of your code seems quite repetitive - why not implement one check that can handle all of these cases?

You can write a statement seeing if sort_by .includes your sort by parameter, and then one reject statement can replace this whole block of repetitive statements.

2023-06-30 08:42 UTC, robert-matthew-brooks commented on models/util.js
> +}
I think this is done on line 55 (and 38), these if statements are checking what model parameters need validating

2023-06-30 08:42 UTC, merged